import { motion } from 'motion/react';
import { Check, Copy, ArrowRight } from 'lucide-react';
import { useState } from 'react';
import { execute_clipboard_copy } from '../utils/clipboard';
import { TopStocksTicker } from './TopStocksTicker';

export function HomeView({ onNavigate }: { onNavigate: () => void }) {
  const [is_copied, set_is_copied] = useState(false);
  const platform_contract = "0x8d104de1d94b9f08f96877ccc1dd0c99757a2743";

  const handle_copy = async () => {
    const success = await execute_clipboard_copy(platform_contract);
    if (success) {
      set_is_copied(true);
      setTimeout(() => set_is_copied(false), 2000);
    }
  };

  return (
    <div className="flex-1 w-full max-w-5xl mx-auto px-6 py-12 md:py-20 flex flex-col justify-center min-h-full">
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="flex flex-col gap-6"
      >
        <div className="inline-block px-3 py-1 bg-[#ccff00]/10 border border-[#ccff00]/30 rounded text-[#ccff00] text-[10px] font-bold tracking-widest uppercase w-fit">
          Decentralized Equity Protocol
        </div>
        
        <h1 className="text-[11vw] sm:text-6xl md:text-8xl lg:text-[120px] font-black italic tracking-tighter uppercase mb-2 flex flex-wrap items-center">
          <span>Stonk</span>
          <span className="relative ml-2 sm:ml-4 md:ml-6 px-4 md:px-8 pt-2 pb-1 md:pt-4 md:pb-2 flex items-center justify-center mt-2 sm:mt-0">
            <span className="absolute inset-0 bg-[#ccff00] rounded-sm -skew-x-[12deg]"></span>
            <span className="relative text-black leading-none z-10">Warz</span>
          </span>
        </h1>
        
        <p className="text-lg md:text-xl text-zinc-400 max-w-2xl leading-relaxed mt-4">
          The next evolution of global trading. Access all the available top stocks in the market via high-performance tokenized infrastructure. 
          Trade top-tier equities with instant settlement, cross-chain composability, and institutional-grade liquidity.
        </p>

        <TopStocksTicker />

        <div className="flex flex-col md:flex-row gap-6 md:gap-8 mt-10 w-full items-start md:items-end">
          <button 
            onClick={onNavigate}
            className="bg-[#ccff00] text-black px-8 font-black uppercase tracking-widest rounded-xl hover:scale-105 transition-transform cursor-pointer flex items-center justify-center gap-2 w-full md:w-auto h-[60px] shrink-0"
          >
            Enter Markets <ArrowRight size={20} />
          </button>
          
          <div className="flex-1 w-full max-w-lg">
            <p className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest mb-2 pl-1">Official Platform Contract</p>
            <div className="bg-[#0a1224]/80 backdrop-blur-xl border border-white/10 rounded-xl p-2 pl-4 flex flex-row items-center gap-3 h-[60px]">
              <div className="overflow-hidden flex-1">
                <p className="text-sm md:text-base font-mono font-bold tracking-tight text-[#ccff00] truncate">
                  {platform_contract}
                </p>
              </div>
              <button 
                onClick={handle_copy}
                className="px-4 py-0 bg-white/5 border border-white/10 text-white font-bold uppercase tracking-widest text-[10px] rounded-lg hover:bg-white/10 transition-colors cursor-pointer flex items-center justify-center gap-2 shrink-0 h-full"
              >
                {is_copied ? <Check size={14} /> : <Copy size={14} />}
                <span className="hidden sm:inline">{is_copied ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
          </div>
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.6 }}
        className="mt-16 md:mt-24"
      >
        <div className="bg-[#0a1224]/80 backdrop-blur-xl border border-[#ccff00]/20 rounded-2xl p-6 md:p-8 flex flex-col justify-center max-w-2xl">
          <div className="inline-block px-3 py-1 bg-[#ccff00]/10 border border-[#ccff00]/30 rounded text-[#ccff00] text-[10px] font-bold tracking-widest uppercase w-fit mb-4">
            How It Works
          </div>
          <h2 className="text-2xl md:text-3xl font-black italic tracking-tighter uppercase mb-4 text-white">
            Creator Fee <span className="text-[#ccff00]">Buybacks</span>
          </h2>
          <p className="text-zinc-400 leading-relaxed text-sm md:text-base">
            100% of all creator fees generated by the protocol are systematically used to execute market buybacks. These repurchased tokens are then distributed as rewards to the top holders, backed by actual stock and the most highly capitalized stock supply in the ecosystem.
          </p>
        </div>
      </motion.div>
    </div>
  );
}
